denso_robot_moveit_demo:
  ros__parameters:
    planning_scene_monitor_options:
      name: "planning_scene_monitor"
      robot_description: "robot_description"
      joint_state_topic: "joint_states"
      attached_collision_object_topic: "/denso_robot_moveit_demo/planning_scene_monitor"
      publish_planning_scene_topic: "/denso_robot_moveit_demo/publish_planning_scene"
      monitored_planning_scene_topic: "/denso_robot_moveit_demo/monitored_planning_scene"
      wait_for_initial_state_timeout: 10.0

    planning_pipelines:
      #namespace: "moveit_cpp"  # optional, default is ~
      pipeline_names: ["ompl"]

    plan_request_params:
      planning_attempts: 10
      planning_pipeline: ompl
      max_velocity_scaling_factor: 1.0
      max_acceleration_scaling_factor: 1.0
