controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    denso_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    denso_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


denso_joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 1000.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    open_loop_control: true
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 0.0